# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [7]:
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
array1=np.arange(10,49)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [6]:
np.shape(array1)

(39,)

5. Print the type of the previous array in question 3

In [7]:
type(array1)

numpy.ndarray

6. Print the numpy version and the configuration


In [31]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Abid Ali/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Abid Ali/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Abid Ali/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mk

7. Print the dimension of the array in question 3


In [8]:
array1.ndim

1

8. Create a boolean array with all the True values

In [10]:
alphabets=np.array(["S","S","S","S"])
alphabets=="S"

array([ True,  True,  True,  True])

9. Create a two dimensional array




In [12]:
array2d=np.array([[1,2,3,4,5],[6,7,8,8,10]])
array2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  8, 10]])

10. Create a three dimensional array



In [13]:
array3d=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
array3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [32]:
new_array=np.arange(10)
print(new_array)
print(new_array[-1::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [36]:
null_vector=np.zeros(10)
null_vector[4]=1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [18]:
identity_matrix=np.eye(3,3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [13]:
float_arr=np.array([1,2,3,4,5]).astype(np.float64)
float_arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [37]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
comparing_arrays=arr1==arr2
comparing_arrays

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [45]:
odd_numbers=np.arange(1,10,2)
odd_numbers

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [50]:
odd_numbers[0:5]=-1
odd_numbers

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [51]:
replacement=np.arange(10)
replacement[5:9]=12
replacement

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [52]:
np.array([[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]])

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [54]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1:2,1:2]=12
arr2d


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0:1,0:1,0:3]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [27]:
arr2d=np.arange(0,10).reshape(2,5)
arr2d
arr2d[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [28]:
arr2d[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [30]:
arr2d[:,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [67]:
random_values_array=np.random.randn(10,10)
print(random_values_array)
maximum=np.max(random_values_array)
minimum=np.min(random_values_array)
print(maximum)
print(minimum)

[[-1.10283157e+00  5.80030228e-01 -2.12510376e+00 -1.29423781e+00
   1.72917174e+00 -1.57460865e+00  2.44717302e+00 -1.28233952e-01
  -1.12914302e+00  9.60379129e-01]
 [ 2.63419207e-01  1.68576749e-01  8.71065981e-01 -5.25402008e-01
   7.85215940e-01  3.08593108e-01  2.34772288e-01 -4.46487488e-01
  -8.12199138e-01 -5.83494350e-01]
 [ 1.35275140e+00  1.49406116e-01  1.35667897e+00  2.35208554e-01
   1.34845353e+00  1.19551273e+00  3.21016497e-01 -2.95650317e-01
  -1.06535669e+00  4.64905311e-01]
 [ 1.09292472e+00 -1.29246538e+00 -5.75454331e-01 -7.16730613e-01
   9.61266269e-01 -1.49029880e+00  9.63947952e-02  1.21413476e+00
   1.32334362e+00  7.30717215e-01]
 [-1.22389017e+00  4.34729575e-01  9.13377402e-01 -4.03176763e-01
  -7.40307570e-01 -3.53546430e-01 -3.02235345e-01  2.45875511e-01
   5.29937626e-01  2.09090935e-01]
 [ 1.45725184e+00  3.53778296e-04 -1.22900956e-01 -2.18990782e-01
   4.47255866e-02  2.90673360e-02 -4.70796652e-01 -4.84386468e-01
   8.06527469e-01 -9.79006132e-01

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [71]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [72]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [74]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
data[names!="Will"]


[[ 0.98939189 -0.61847344 -1.61350108 -1.97377959]
 [ 0.98362944 -0.24733778  1.17867537  1.81554074]
 [-0.06681544 -0.27975558 -0.54256514 -0.25822662]
 [ 0.21902326 -1.07648933  1.19320386  1.26895118]
 [ 0.79407207  0.27924513  0.56192775 -0.65280193]
 [-0.71031506 -1.3906428  -0.96394268 -0.24873466]
 [ 0.70844267 -0.6085306   0.33355079  1.62731309]]


array([[ 0.98939189, -0.61847344, -1.61350108, -1.97377959],
       [ 0.98362944, -0.24733778,  1.17867537,  1.81554074],
       [ 0.21902326, -1.07648933,  1.19320386,  1.26895118],
       [-0.71031506, -1.3906428 , -0.96394268, -0.24873466],
       [ 0.70844267, -0.6085306 ,  0.33355079,  1.62731309]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [75]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names=="Bob"]


array([[ 0.48691244, -0.84276971, -1.27358098,  1.08207874],
       [ 0.99823395, -0.82573464,  0.84065919,  0.37680388]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [7]:
array_sqrt=np.arange(10)
square_root=np.sqrt(array_sqrt)
square_root
np.where(square_root<0.5,0,square_root)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [8]:
array_1=np.random.randn(12)
array_2=np.random.randn(12)
np.maximum(array_1,array_2)

array([ 0.8555475 ,  0.99606915,  1.01632892,  0.84068672,  1.23752779,
        1.39251977,  1.14594234, -0.99734967,  0.52511048,  1.42698337,
        0.11277801,  1.27637434])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [93]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names=np.unique(names)
unique_names
sorted(unique_names)

['Bob', 'Joe', 'Will']

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [82]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [14]:
random_values=np.random.randn(20)
random_values.cumsum()

array([-0.15652193, -0.62547463,  0.4663216 ,  1.28572933,  2.42061137,
        2.06141194,  2.2077738 ,  4.75170283,  5.73878376,  6.80582177,
        7.30843265,  8.0552183 ,  7.53394065,  8.15913993,  7.56138045,
        7.53018883,  7.12439063,  7.7052409 ,  7.09904088,  7.1461186 ])