# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [7]:
arr1=np.arange(10).reshape(2,5)
arr2=np.ones((2,5),dtype="int32")
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [8]:
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [9]:
arr3=np.arange(10).reshape(2,5)
arr3.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [13]:
arr4=np.arange(15).reshape(3,5)
arr4.flatten()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [14]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [18]:
arr5=np.arange(25).reshape(5,5)
arr5*arr5

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [19]:
arr6=np.arange(30).reshape(5,6)
print(arr6)
np.mean(arr6)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [20]:
np.std(arr6)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [21]:
np.median(arr6)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [23]:
arr6.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [33]:
arr7=np.arange(16).reshape(4,4)
print(arr7)
np.trace(arr7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [35]:
np.linalg.det(arr7)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [28]:
fifth_percentile=np.percentile(arr7,5)
print(fifth_percentile)
ninety_fifth_percentile=np.percentile(arr7,95)
print(ninety_fifth_percentile)

0.75
14.25


## Question:15

### How to find if a given array has any null values?

In [30]:
(arr7==0).any()

True